image:
  width: 400
  height: 300

camera:
  viewport_height: 2.0
  focal_length: 1.0

sphere:
  center: [0.0, 0.0, -1.0]
  radius: 0.5

plane:
  point: [0.0, -0.5, 0.0]
  normal: [0.0, 1.0, 0.0]

lighting:
  ambient_color: [0.1, 0.1, 0.1]
  object_color: [0.0, 1.0, 0.0] 
  specular_color: [1.0, 1.0, 1.0]
  light_position: [2.0, 2.0, 1.0]
  light_color: [1.0, 1.0, 1.0]
  shadow_intensity: 0.5
